### PR TITLE
Feature/enable iso transfer

### PR DESCRIPTION
**Pull request by hroest**
This PR changes the way requantAlignedValues.py write output files, instead of only writing the changed peakgroups it will now in all cases write all peakgroups. 

This is due to the fact that the script may, with `isotopic_transfer` enabled, change the position and intensity of *any* peakgroup and we cannot predict which peakgroups it will not touch and which ones it will impute. Therefore it is easiest to write out all peakgroups and then aggregate them into the final output

This also changes the runner script in the aggregation step as now the original input file does not need to be added any more

### CODE REVIEW

**Comment by grosenberger** [comment]
:+1:

**Comment by lcb** [comment]
Changes to the runner script look good

**Comment by hroest** [comment]
@lcb does it work on iportal with the new script? Do you get the same
results?

sent from my smartphone -- you may keep any typos you find.

**Comment by lcb** [comment]
The changes to requantAlignedValues.py are different than I expected. The current version does not work correctly!
So far, when doing requantAlignedValues.py --single_run only the requantified peaks were written. At the final step the feature_alignment + all requant files were merged to one.
Now, each requantAlignedValues run writes out the full feature_alignment file. Thus combining multiple requant output files leads to many duplicate entries.

```
requantAlignedParallel.sh --peakgroups_infile feature_alignment.tsv --out old.tsv --out_matrix old.matrix.tsv --in ??/*.tr
source ...
requantAlignedParallel.sh --peakgroups_infile feature_alignment.tsv --out new.tsv --out_matrix new.matrix.tsv --in ??/*.tr
wc *.tsv
     841     6728    96421 new.matrix.tsv
     841     6728    96421 old.matrix.tsv
    7299   351672  7033291 new.tsv
    2521   122328  2408845 old.tsv
```

**Comment by lcb** [comment]
Simpler example:

```
requantAlignedValues.py --peakgroups_infile feature_alignment.tsv --out new/old.single.tsv --do_single_run 18/chludwig_L110830_18_SW_with_dscore_filtered-0_2-0_2.tr --in ??/*.tr
wc *.single.tsv
   2431  117108 2343388 new.single.tsv
     42    2436   31165 old.single.tsv
```

**Comment by hroest** [comment]
@lcb you are right, now it simply writes out _all_ peakgroups. That is not so great behavior. Can you try #35, this should fix the issue

**Comment by lcb** [comment]
Question: Does isotopic_transfer work for requant now? Shall I enable the option in iportal?

**Comment by hroest** [comment]
yes, it should work with this PR and with #35 and #36 all errors should be fixed as well. Maybe try it first, on a dataset without isotopic information and without any charge states it should give the same results as before

**Pull request merged**
