### PR TITLE
Update spectrast2spectrast_irt.py

### PR DESCRIPTION
**Pull request by guoci**

### CODE REVIEW

**Comment by hroest** [comment]
@grosenberger what was the reason to use `wb` here, is this so that the tests run on Windows as well?

**Comment by grosenberger** [comment]
I don't remember, as we switched to the reimplementation in SpectraST especially on Windows some time ago. @guoci did you encounter any problems with `wb`?

**Comment by guoci** [comment]
Hi @grosenberger , 'wb' will not work with Python 3, because bytes are expected, but str is written to the file object.

**Comment by hroest** [comment]
makes a lot of sense, :+1:

**Comment by grosenberger** [comment]
Great, thanks for the patch!

**Pull request merged**
