### PR TITLE
Feature/python3

### PR DESCRIPTION
**Pull request by hroest**
enable most of the library to work with Python 3

176 / 182 tests run with Python3

I have disabled the remaining 6 tests as they would not run well with Python3, thus there is still some work to do here.

### CODE REVIEW

**Comment by hroest** [comment]
as this is quite some invasive change, I would like to get some feedback from people what they think

**Comment by grosenberger** [comment]
I have briefly looked at the changes and I think we should go ahead with the merge. There might be some functions that will run into problems (because they were not tested), but the most important components (spectrast2tsv.py and feature_alignment.py) seem to be fully compatible.

**Comment by mesontau** [comment]
As far as I see spectrast2tsv.py will not be compatible with Python3 (for the moment), right? Anyway I think we should go ahead, and make the remaining pieces compatible as soon as we can.

**Comment by hroest** [comment]
yes, spectrast2tsv is currently not compatible with Python3. While it does compile and run, the results are different than those in the tests so I dont feel comfortable to let someone use it. I didnt investigate futher as I dont have much understanding of the code there ...

**Comment by mesontau** [comment]
I will have a look over the weekend. Hopefully it is not going to be very hard to solve.

**Comment by aseyboldt** [comment]
I could really use python3 support in a project I am working on, so I had a look at this issue in `spectrast2tsv`. It turn out the problem is in `data_structures/peak.py`. This should fix it:

```diff
diff --git a/msproteomicstoolslib/data_structures/peak.py b/msproteomicstoolslib/data_structures/peak.py
index 6948615..45da10f 100644
--- a/msproteomicstoolslib/data_structures/peak.py
+++ b/msproteomicstoolslib/data_structures/peak.py
@@ -229,7 +229,7 @@ class Peak:
         #is_not_unique
         if '[' in first_interp :
             self.is_not_unique = True
-            first_interp = filter(lambda x: x not in ['[',']'], first_interp)
+            first_interp = first_interp.strip("[]")

         if str(first_interp)[0] == 'I':
             self.is_immonium = True
```

I could send you a pull request for your pull request, but I guess that would be overkill :-)

**Comment by hroest** [comment]
@aseyboldt thanks for the patch, however when I apply the patch and try to run the tests I still get different results on Py2 and Py3 so I dont think we are quite there yet. Do you have any idea what is still missing? So is your project requiring specifically `spectrast2tsv` to be ported to Python3 or general functionality in msproteomicstools ?

**Comment by aseyboldt** [comment]
@hroest I am using msproteomicstools to create libraries for openswath. Is this still the recommended way to do this? Without py3 I would have to use two different virtualenvs side by side, one for msproteomicstools and one for snakemake. It's very much possible, but seems like some trouble.

About py3 compatibility. I found 2 more bugs, both in `math.smoothing.WeightedNearestNeighbour` (see https://github.com/aseyboldt/msproteomicstools/commits/feature/python3 for the commits):

1. The binary search implementation was broken for python3. I could not find any other part of the library that used that so I just replaced it by `np.searchsorted` and removed it.

2. This is acually not py3 related, and I am not completely sure. You can find the diff at https://github.com/aseyboldt/msproteomicstools/commit/19c9bc06a5811bc05ed725fe2c4585494e7c0539. In line 742 you use `self.min_diff` as an element of the weights, when it should be `1/(abs(self.min_diff)**EXP)` (I think). The expected smoothed values in the test (test_Smoothing::TestUnitSmoothing.test_smooth_nn) seemed weird too, because the max of the non-smoothed values is 15 and the max of the smoothed values is 15.6. I did not adujst the tests, and for me that is the only test that does not succeed with both python2.7 and python3.4. It fails the same way in py2 and py3 however.

**Comment by hroest** [comment]
@aseyboldt sorry for the long break, I was on vacation for a few months and moved to the US, so I did not have time to look into this for quite some time

1. great, thanks a lot
2. This is part of the algorithm to not give too much weight if there is a point "very close" and it would get 1/d weight where d would be very small. I thought that this would help to not put undue weight on a point that just happens to be very close to the interpolation point. But you are right, I think it should be 
```
=[ 1/(abs(s)**EXP) if s > self.min_diff else 1/(abs(self.min_diff)**EXP) for s in source_d_diff]
```

**Comment by aseyboldt** [comment]
@hroest no worries, I hope you had a nice vacation.
About 2.: I think the patch should do the same as the code you posted, only without the exponent `EXP`. I didn't put it in since it was hard coded to 1 anyway.

**Comment by hroest** [comment]
so I have added all your changes, and merged with the current master. So it seems we are ready to merge and I have the last tests working on my machine in Py2 and Py3. That was a surprising amount of work and pain ... lets hope that travis agrees!

**Comment by hroest** [comment]
@aseyboldt currently using msproteomicstools is still the recommended way to do it, see also our Nature protocols paper http://www.ncbi.nlm.nih.gov/pubmed/25675208 
I think @grosenberger can comment more on ongoing efforts to port some of the functions into other projects such as OpenMS or the TPP - I think we want to have the functionality in C++ and inside a larger project rather than in a bunch of scripts here that  need to be run separately

**Comment by hroest** [comment]
all 182 tests work in all 3 configurations ...

**Comment by aseyboldt** [comment]
All 182 Tests pass on my machine too, if I install @hroest's fork of `scikit.datasmooth`. The pip installed version still fails.
Also, the `setup.py` in datasmooth imports numpy, which means that installing it into an empty virtualenv fails (The setup script tries to import numpy before it is installed). If nobody beats me to it I will send a pull request to datasmooth on monday or thu.

**Comment by aseyboldt** [comment]
The datasmooth issues are jjstickel/scikit-datasmooth#2

**Comment by hroest** [comment]
looks like it is ready to merge - any further comments from @mesontau or @grosenberger  ?

**Comment by grosenberger** [comment]
Looks good to me!

**Comment by mesontau** [comment]
It looks good to me! Thanks for your hard work!

Enviado desde mi iPhone

**Pull request merged**
